### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by adam-sokolowski** [gangsthub/vue-exercises#4]
I kept getting the following issue when executing `npm run dev` from nuxt.config.js

`Syntax Error: Unexpected token (94:20)
  93 |                 config.hotMiddleware = {
> 94 |                     ...{config.hotMiddleware},
     |                     ^
  95 |                     plugins: [
  96 |                         ...config.hotMiddleware.plugins,
  97 |                         new webpack.HotModuleReplacementPlugin(),
`

to fix it and keep HMR I changed it to:

```TS
config.hotMiddleware = [
    ...config.hotMiddleware,
    ...[
        ...config.hotMiddleware.plugins,
        new webpack.HotModuleReplacementPlugin(),
    ]
]
```

**Comment by paulmelero** [comment]
Should be fixed now (#5). Thanks a lot! ;)
